name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Congratulation for your first workflow"
      - name: Print Goodbye
        run: |
          echo "Created by Harsh on 26 Nov"
          echo "Keep working hard"
